import 'dart:convert';
import 'dart:math';
import 'package:sky/framework/debug/tracing.dart';
import 'package:sky/framework/net/fetch.dart';

class MostWanted {
  String date;
  String title;
  String strapline;
  String link;
  String category;
  String image;
  String detail;

  MostWanted(this.date, this.title, this.strapline, this.link, this.category, this.image, this.detail);

}


class MostWantedDataFetcher {
  String url;


  MostWantedDataFetcher(this.url);

  List<MostWanted> fetchData() {
    List<MostWanted> list = new List<MostWanted>();
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    list.add(new MostWanted('24 April 2015', 'Man wanted for hilarity', 'This man is hilarious', 'A link', 'Most Wanted', 'http://riveronline.co.uk/wp-content/uploads/2014/10/UK-Independence-Party-UKIP-leader-Nigel-Farage.jpg', "Nigel Farage"));
    return list;
  }
  //todo
}
